name: CI

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: adicionando mensagens de log
        run: |
          echo "::debug:: Mensagem de Log Debug"
          echo "::warning:: Mensagem de Log warning"
          echo "::notice:: Mensagem de Log notice"
          echo "::error:: Mensagem de Log de Error executado por ${{ github.actor }}"
          
          
